//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.28 at 10:45:07 AM EDT
//

package dev.ebullient.fc5.json2xml.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for compendiumType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="compendiumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="item" type="{}itemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="race" type="{}raceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="class" type="{}classType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="feat" type="{}featType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="background" type="{}backgroundType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="spell" type="{}spellType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="monster" type="{}monsterType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="auto_indent" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "compendium")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compendiumType", propOrder = {
        "elements"
})
public class XmlCompendiumType {

    @XmlElements({
            @XmlElement(name = "background", type = XmlBackgroundType.class),
            @XmlElement(name = "class", type = XmlClassType.class),
            @XmlElement(name = "feat", type = XmlFeatType.class),
            @XmlElement(name = "item", type = XmlItemType.class),
            @XmlElement(name = "monster", type = XmlMonsterType.class),
            @XmlElement(name = "race", type = XmlRaceType.class),
            @XmlElement(name = "spell", type = XmlSpellType.class),
    })
    protected List<Object> elements;

    @XmlAttribute(name = "version")
    protected Byte version;

    @XmlAttribute(name = "auto_indent")
    protected String autoIndent;

    /**
     * Gets the value of the itemOrRaceOrClazz property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemOrRaceOrClazz property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getItemOrRaceOrClazz().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlItemType }
     * {@link XmlRaceType }
     * {@link XmlClassType }
     * {@link XmlFeatType }
     * {@link XmlBackgroundType }
     * {@link XmlSpellType }
     * {@link XmlMonsterType }
     *
     *
     */
    public List<Object> getElements() {
        if (elements == null) {
            elements = new ArrayList<Object>();
        }
        return this.elements;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *         possible object is
     *         {@link Byte }
     *
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *        allowed object is
     *        {@link Byte }
     *
     */
    public void setVersion(Byte value) {
        this.version = value;
    }

    /**
     * Gets the value of the autoIndent property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getAutoIndent() {
        return autoIndent;
    }

    /**
     * Sets the value of the autoIndent property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setAutoIndent(String value) {
        this.autoIndent = value;
    }

}
