//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.28 at 10:45:07 AM EDT
//

package dev.ebullient.fc5.json2xml.jaxb;

import dev.ebullient.fc5.pojo.SchoolEnum;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for schoolEnum.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="schoolEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="D"/>
 *     &lt;enumeration value="EN"/>
 *     &lt;enumeration value="EV"/>
 *     &lt;enumeration value="I"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="T"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "schoolEnum")
@XmlEnum
public enum XmlSchoolEnum {

    A,
    C,
    D,
    EN,
    EV,
    I,
    N,
    T;

    public String value() {
        return name();
    }

    public static XmlSchoolEnum fromValue(String v) {
        if ("V".equals(v)) {
            return EV;
        }
        if ("E".equals(v)) {
            return EN;
        }
        return valueOf(v);
    }

    public static XmlSchoolEnum fromValue(SchoolEnum s) {
        return fromValue(s.getEncodedValue());
    }
}
