//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.28 at 10:45:07 AM EDT
//

package dev.ebullient.fc5.json2xml.jaxb;

import dev.ebullient.fc5.pojo.SizeEnum;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for sizeEnum.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 *
 * <pre>
 * &lt;simpleType name="sizeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="L"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="G"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "sizeEnum")
@XmlEnum
public enum XmlSizeEnum {

    T,
    S,
    M,
    L,
    H,
    G;

    public String value() {
        return name();
    }

    public static XmlSizeEnum fromValue(String v) {
        return valueOf(v);
    }

    public static XmlSizeEnum fromValue(SizeEnum v) {
        if (v == SizeEnum.VARIES || v == SizeEnum.S_OR_M) {
            return M;
        }
        return valueOf(v.getEncodedValue());
    }
}
