//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.28 at 10:45:07 AM EDT
//

package dev.ebullient.fc5.xml;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the dev.ebullient.fc5.xml package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class XmlObjectFactory {

    private final static QName _Compendium_QNAME = new QName("", "compendium");
    private final static QName _TraitTypeSpecial_QNAME = new QName("", "special");
    private final static QName _TraitTypeRecharge_QNAME = new QName("", "recharge");
    private final static QName _TraitTypeAttack_QNAME = new QName("", "attack");
    private final static QName _TraitTypeName_QNAME = new QName("", "name");
    private final static QName _TraitTypeText_QNAME = new QName("", "text");
    private final static QName _TraitTypeProficiency_QNAME = new QName("", "proficiency");
    private final static QName _SpellTypeDuration_QNAME = new QName("", "duration");
    private final static QName _SpellTypeComponents_QNAME = new QName("", "components");
    private final static QName _SpellTypeLevel_QNAME = new QName("", "level");
    private final static QName _SpellTypeSchool_QNAME = new QName("", "school");
    private final static QName _SpellTypeRitual_QNAME = new QName("", "ritual");
    private final static QName _SpellTypeClasses_QNAME = new QName("", "classes");
    private final static QName _SpellTypeRoll_QNAME = new QName("", "roll");
    private final static QName _SpellTypeRange_QNAME = new QName("", "range");
    private final static QName _SpellTypeTime_QNAME = new QName("", "time");
    private final static QName _SpellTypeSource_QNAME = new QName("", "source");
    private final static QName _BackgroundTypeTrait_QNAME = new QName("", "trait");
    private final static QName _MonsterTypeCon_QNAME = new QName("", "con");
    private final static QName _MonsterTypeSenses_QNAME = new QName("", "senses");
    private final static QName _MonsterTypeHp_QNAME = new QName("", "hp");
    private final static QName _MonsterTypeSave_QNAME = new QName("", "save");
    private final static QName _MonsterTypeDescription_QNAME = new QName("", "description");
    private final static QName _MonsterTypeType_QNAME = new QName("", "type");
    private final static QName _MonsterTypeSpeed_QNAME = new QName("", "speed");
    private final static QName _MonsterTypeConditionImmune_QNAME = new QName("", "conditionImmune");
    private final static QName _MonsterTypeVulnerable_QNAME = new QName("", "vulnerable");
    private final static QName _MonsterTypeDex_QNAME = new QName("", "dex");
    private final static QName _MonsterTypeLegendary_QNAME = new QName("", "legendary");
    private final static QName _MonsterTypeSkill_QNAME = new QName("", "skill");
    private final static QName _MonsterTypeAction_QNAME = new QName("", "action");
    private final static QName _MonsterTypeSpells_QNAME = new QName("", "spells");
    private final static QName _MonsterTypeCha_QNAME = new QName("", "cha");
    private final static QName _MonsterTypeWis_QNAME = new QName("", "wis");
    private final static QName _MonsterTypeAc_QNAME = new QName("", "ac");
    private final static QName _MonsterTypeImmune_QNAME = new QName("", "immune");
    private final static QName _MonsterTypeReaction_QNAME = new QName("", "reaction");
    private final static QName _MonsterTypeLanguages_QNAME = new QName("", "languages");
    private final static QName _MonsterTypeResist_QNAME = new QName("", "resist");
    private final static QName _MonsterTypePassive_QNAME = new QName("", "passive");
    private final static QName _MonsterTypeInt_QNAME = new QName("", "int");
    private final static QName _MonsterTypeCr_QNAME = new QName("", "cr");
    private final static QName _MonsterTypeStr_QNAME = new QName("", "str");
    private final static QName _MonsterTypeSlots_QNAME = new QName("", "slots");
    private final static QName _MonsterTypeEnvironment_QNAME = new QName("", "environment");
    private final static QName _MonsterTypeSize_QNAME = new QName("", "size");
    private final static QName _MonsterTypeAlignment_QNAME = new QName("", "alignment");
    private final static QName _AutolevelTypeFeature_QNAME = new QName("", "feature");
    private final static QName _AutolevelTypeCounter_QNAME = new QName("", "counter");
    private final static QName _ItemTypeMagic_QNAME = new QName("", "magic");
    private final static QName _ItemTypeStrength_QNAME = new QName("", "strength");
    private final static QName _ItemTypeModifier_QNAME = new QName("", "modifier");
    private final static QName _ItemTypeWeight_QNAME = new QName("", "weight");
    private final static QName _ItemTypeStealth_QNAME = new QName("", "stealth");
    private final static QName _ItemTypeProperty_QNAME = new QName("", "property");
    private final static QName _ItemTypeDmgType_QNAME = new QName("", "dmgType");
    private final static QName _ItemTypeDetail_QNAME = new QName("", "detail");
    private final static QName _ItemTypeDmg2_QNAME = new QName("", "dmg2");
    private final static QName _ItemTypeDmg1_QNAME = new QName("", "dmg1");
    private final static QName _ItemTypeValue_QNAME = new QName("", "value");
    private final static QName _FeatTypePrerequisite_QNAME = new QName("", "prerequisite");
    private final static QName _ClassTypeAutolevel_QNAME = new QName("", "autolevel");
    private final static QName _ClassTypeWealth_QNAME = new QName("", "wealth");
    private final static QName _ClassTypeArmor_QNAME = new QName("", "armor");
    private final static QName _ClassTypeNumSkills_QNAME = new QName("", "numSkills");
    private final static QName _ClassTypeSlotsReset_QNAME = new QName("", "slotsReset");
    private final static QName _ClassTypeHd_QNAME = new QName("", "hd");
    private final static QName _ClassTypeWeapons_QNAME = new QName("", "weapons");
    private final static QName _ClassTypeTools_QNAME = new QName("", "tools");
    private final static QName _ClassTypeSpellAbility_QNAME = new QName("", "spellAbility");
    private final static QName _RaceTypeAbility_QNAME = new QName("", "ability");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
     * dev.ebullient.fc5.xml
     *
     */
    public XmlObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlCompendiumType }
     *
     */
    public XmlCompendiumType createCompendiumType() {
        return new XmlCompendiumType();
    }

    /**
     * Create an instance of {@link XmlItemType }
     *
     */
    public XmlItemType createItemType() {
        return new XmlItemType();
    }

    /**
     * Create an instance of {@link XmlRaceType }
     *
     */
    public XmlRaceType createRaceType() {
        return new XmlRaceType();
    }

    /**
     * Create an instance of {@link XmlModifierType }
     *
     */
    public XmlModifierType createModifierType() {
        return new XmlModifierType();
    }

    /**
     * Create an instance of {@link XmlFeatType }
     *
     */
    public XmlFeatType createFeatType() {
        return new XmlFeatType();
    }

    /**
     * Create an instance of {@link XmlTraitType }
     *
     */
    public XmlTraitType createTraitType() {
        return new XmlTraitType();
    }

    /**
     * Create an instance of {@link XmlMonsterType }
     *
     */
    public XmlMonsterType createMonsterType() {
        return new XmlMonsterType();
    }

    /**
     * Create an instance of {@link XmlFeatureType }
     *
     */
    public XmlFeatureType createFeatureType() {
        return new XmlFeatureType();
    }

    /**
     * Create an instance of {@link XmlAutolevelType }
     *
     */
    public XmlAutolevelType createAutolevelType() {
        return new XmlAutolevelType();
    }

    /**
     * Create an instance of {@link XmlBackgroundType }
     *
     */
    public XmlBackgroundType createBackgroundType() {
        return new XmlBackgroundType();
    }

    /**
     * Create an instance of {@link XmlSlotsType }
     *
     */
    public XmlSlotsType createSlotsType() {
        return new XmlSlotsType();
    }

    /**
     * Create an instance of {@link XmlCounterType }
     *
     */
    public XmlCounterType createCounterType() {
        return new XmlCounterType();
    }

    /**
     * Create an instance of {@link XmlSpellType }
     *
     */
    public XmlSpellType createSpellType() {
        return new XmlSpellType();
    }

    /**
     * Create an instance of {@link XmlClassType }
     *
     */
    public XmlClassType createClassType() {
        return new XmlClassType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCompendiumType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "compendium")
    public JAXBElement<XmlCompendiumType> createCompendium(XmlCompendiumType value) {
        return new JAXBElement<XmlCompendiumType>(_Compendium_QNAME, XmlCompendiumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "special", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeSpecial(String value) {
        return new JAXBElement<String>(_TraitTypeSpecial_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "recharge", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeRecharge(String value) {
        return new JAXBElement<String>(_TraitTypeRecharge_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "attack", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeAttack(String value) {
        return new JAXBElement<String>(_TraitTypeAttack_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeText(String value) {
        return new JAXBElement<String>(_TraitTypeText_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlTraitType.class)
    public JAXBElement<String> createTraitTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlTraitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "duration", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeDuration(String value) {
        return new JAXBElement<String>(_SpellTypeDuration_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "components", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeComponents(String value) {
        return new JAXBElement<String>(_SpellTypeComponents_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "level", scope = XmlSpellType.class)
    public JAXBElement<BigInteger> createSpellTypeLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_SpellTypeLevel_QNAME, BigInteger.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSchoolEnum }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "school", scope = XmlSpellType.class)
    public JAXBElement<XmlSchoolEnum> createSpellTypeSchool(XmlSchoolEnum value) {
        return new JAXBElement<XmlSchoolEnum>(_SpellTypeSchool_QNAME, XmlSchoolEnum.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ritual", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeRitual(String value) {
        return new JAXBElement<String>(_SpellTypeRitual_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "classes", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeClasses(String value) {
        return new JAXBElement<String>(_SpellTypeClasses_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "roll", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeRoll(String value) {
        return new JAXBElement<String>(_SpellTypeRoll_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "range", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeRange(String value) {
        return new JAXBElement<String>(_SpellTypeRange_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "time", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeTime(String value) {
        return new JAXBElement<String>(_SpellTypeTime_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "source", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeSource(String value) {
        return new JAXBElement<String>(_SpellTypeSource_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text", scope = XmlSpellType.class)
    public JAXBElement<String> createSpellTypeText(String value) {
        return new JAXBElement<String>(_TraitTypeText_QNAME, String.class, XmlSpellType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlBackgroundType.class)
    public JAXBElement<String> createBackgroundTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlBackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = XmlBackgroundType.class)
    public JAXBElement<XmlTraitType> createBackgroundTypeTrait(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_BackgroundTypeTrait_QNAME, XmlTraitType.class, XmlBackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlBackgroundType.class)
    public JAXBElement<String> createBackgroundTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlBackgroundType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "con", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeCon(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeCon_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "senses", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeSenses(String value) {
        return new JAXBElement<String>(_MonsterTypeSenses_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "hp", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeHp(String value) {
        return new JAXBElement<String>(_MonsterTypeHp_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "save", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeSave(String value) {
        return new JAXBElement<String>(_MonsterTypeSave_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "description", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeDescription(String value) {
        return new JAXBElement<String>(_MonsterTypeDescription_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "type", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeType(String value) {
        return new JAXBElement<String>(_MonsterTypeType_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "speed", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeSpeed(String value) {
        return new JAXBElement<String>(_MonsterTypeSpeed_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "conditionImmune", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeConditionImmune(String value) {
        return new JAXBElement<String>(_MonsterTypeConditionImmune_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "vulnerable", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeVulnerable(String value) {
        return new JAXBElement<String>(_MonsterTypeVulnerable_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "dex", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeDex(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeDex_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "legendary", scope = XmlMonsterType.class)
    public JAXBElement<XmlTraitType> createMonsterTypeLegendary(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_MonsterTypeLegendary_QNAME, XmlTraitType.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "skill", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeSkill(String value) {
        return new JAXBElement<String>(_MonsterTypeSkill_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = XmlMonsterType.class)
    public JAXBElement<XmlTraitType> createMonsterTypeTrait(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_BackgroundTypeTrait_QNAME, XmlTraitType.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "action", scope = XmlMonsterType.class)
    public JAXBElement<XmlTraitType> createMonsterTypeAction(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_MonsterTypeAction_QNAME, XmlTraitType.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "spells", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeSpells(String value) {
        return new JAXBElement<String>(_MonsterTypeSpells_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "cha", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeCha(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeCha_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "wis", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeWis(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeWis_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ac", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeAc(String value) {
        return new JAXBElement<String>(_MonsterTypeAc_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "immune", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeImmune(String value) {
        return new JAXBElement<String>(_MonsterTypeImmune_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "reaction", scope = XmlMonsterType.class)
    public JAXBElement<XmlTraitType> createMonsterTypeReaction(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_MonsterTypeReaction_QNAME, XmlTraitType.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "languages", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeLanguages(String value) {
        return new JAXBElement<String>(_MonsterTypeLanguages_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "resist", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeResist(String value) {
        return new JAXBElement<String>(_MonsterTypeResist_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "passive", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypePassive(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypePassive_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "int", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeInt(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeInt_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "cr", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeCr(String value) {
        return new JAXBElement<String>(_MonsterTypeCr_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "str", scope = XmlMonsterType.class)
    public JAXBElement<BigInteger> createMonsterTypeStr(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeStr_QNAME, BigInteger.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSlotsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "slots", scope = XmlMonsterType.class)
    public JAXBElement<XmlSlotsType> createMonsterTypeSlots(XmlSlotsType value) {
        return new JAXBElement<XmlSlotsType>(_MonsterTypeSlots_QNAME, XmlSlotsType.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "environment", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeEnvironment(String value) {
        return new JAXBElement<String>(_MonsterTypeEnvironment_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSizeEnum }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "size", scope = XmlMonsterType.class)
    public JAXBElement<XmlSizeEnum> createMonsterTypeSize(XmlSizeEnum value) {
        return new JAXBElement<XmlSizeEnum>(_MonsterTypeSize_QNAME, XmlSizeEnum.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "alignment", scope = XmlMonsterType.class)
    public JAXBElement<String> createMonsterTypeAlignment(String value) {
        return new JAXBElement<String>(_MonsterTypeAlignment_QNAME, String.class, XmlMonsterType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSlotsType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "slots", scope = XmlAutolevelType.class)
    public JAXBElement<XmlSlotsType> createAutolevelTypeSlots(XmlSlotsType value) {
        return new JAXBElement<XmlSlotsType>(_MonsterTypeSlots_QNAME, XmlSlotsType.class, XmlAutolevelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlFeatureType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "feature", scope = XmlAutolevelType.class)
    public JAXBElement<XmlFeatureType> createAutolevelTypeFeature(XmlFeatureType value) {
        return new JAXBElement<XmlFeatureType>(_AutolevelTypeFeature_QNAME, XmlFeatureType.class, XmlAutolevelType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlCounterType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "counter", scope = XmlAutolevelType.class)
    public JAXBElement<XmlCounterType> createAutolevelTypeCounter(XmlCounterType value) {
        return new JAXBElement<XmlCounterType>(_AutolevelTypeCounter_QNAME, XmlCounterType.class, XmlAutolevelType.class,
                value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "magic", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeMagic(String value) {
        return new JAXBElement<String>(_ItemTypeMagic_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ac", scope = XmlItemType.class)
    public JAXBElement<BigInteger> createItemTypeAc(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeAc_QNAME, BigInteger.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "strength", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeStrength(String value) {
        return new JAXBElement<String>(_ItemTypeStrength_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlModifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = XmlItemType.class)
    public JAXBElement<XmlModifierType> createItemTypeModifier(XmlModifierType value) {
        return new JAXBElement<XmlModifierType>(_ItemTypeModifier_QNAME, XmlModifierType.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "roll", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeRoll(String value) {
        return new JAXBElement<String>(_SpellTypeRoll_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "weight", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeWeight(String value) {
        return new JAXBElement<String>(_ItemTypeWeight_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "range", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeRange(String value) {
        return new JAXBElement<String>(_SpellTypeRange_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlItemEnum }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "type", scope = XmlItemType.class)
    public JAXBElement<XmlItemEnum> createItemTypeType(XmlItemEnum value) {
        return new JAXBElement<XmlItemEnum>(_MonsterTypeType_QNAME, XmlItemEnum.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "stealth", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeStealth(String value) {
        return new JAXBElement<String>(_ItemTypeStealth_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "property", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeProperty(String value) {
        return new JAXBElement<String>(_ItemTypeProperty_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "dmgType", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeDmgType(String value) {
        return new JAXBElement<String>(_ItemTypeDmgType_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "detail", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeDetail(String value) {
        return new JAXBElement<String>(_ItemTypeDetail_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeText(String value) {
        return new JAXBElement<String>(_TraitTypeText_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "dmg2", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeDmg2(String value) {
        return new JAXBElement<String>(_ItemTypeDmg2_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "dmg1", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeDmg1(String value) {
        return new JAXBElement<String>(_ItemTypeDmg1_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "value", scope = XmlItemType.class)
    public JAXBElement<String> createItemTypeValue(String value) {
        return new JAXBElement<String>(_ItemTypeValue_QNAME, String.class, XmlItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "special", scope = XmlFeatType.class)
    public JAXBElement<String> createFeatTypeSpecial(String value) {
        return new JAXBElement<String>(_TraitTypeSpecial_QNAME, String.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlModifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = XmlFeatType.class)
    public JAXBElement<XmlModifierType> createFeatTypeModifier(XmlModifierType value) {
        return new JAXBElement<XmlModifierType>(_ItemTypeModifier_QNAME, XmlModifierType.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlFeatType.class)
    public JAXBElement<String> createFeatTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "prerequisite", scope = XmlFeatType.class)
    public JAXBElement<String> createFeatTypePrerequisite(String value) {
        return new JAXBElement<String>(_FeatTypePrerequisite_QNAME, String.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text", scope = XmlFeatType.class)
    public JAXBElement<String> createFeatTypeText(String value) {
        return new JAXBElement<String>(_TraitTypeText_QNAME, String.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlFeatType.class)
    public JAXBElement<String> createFeatTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlFeatType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAutolevelType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "autolevel", scope = XmlClassType.class)
    public JAXBElement<XmlAutolevelType> createClassTypeAutolevel(XmlAutolevelType value) {
        return new JAXBElement<XmlAutolevelType>(_ClassTypeAutolevel_QNAME, XmlAutolevelType.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "wealth", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeWealth(String value) {
        return new JAXBElement<String>(_ClassTypeWealth_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "armor", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeArmor(String value) {
        return new JAXBElement<String>(_ClassTypeArmor_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "numSkills", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeNumSkills(String value) {
        return new JAXBElement<String>(_ClassTypeNumSkills_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlResetEnum }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "slotsReset", scope = XmlClassType.class)
    public JAXBElement<XmlResetEnum> createClassTypeSlotsReset(XmlResetEnum value) {
        return new JAXBElement<XmlResetEnum>(_ClassTypeSlotsReset_QNAME, XmlResetEnum.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "hd", scope = XmlClassType.class)
    public JAXBElement<BigInteger> createClassTypeHd(BigInteger value) {
        return new JAXBElement<BigInteger>(_ClassTypeHd_QNAME, BigInteger.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "weapons", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeWeapons(String value) {
        return new JAXBElement<String>(_ClassTypeWeapons_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "tools", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeTools(String value) {
        return new JAXBElement<String>(_ClassTypeTools_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "spellAbility", scope = XmlClassType.class)
    public JAXBElement<String> createClassTypeSpellAbility(String value) {
        return new JAXBElement<String>(_ClassTypeSpellAbility_QNAME, String.class, XmlClassType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "special", scope = XmlFeatureType.class)
    public JAXBElement<String> createFeatureTypeSpecial(String value) {
        return new JAXBElement<String>(_TraitTypeSpecial_QNAME, String.class, XmlFeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlModifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = XmlFeatureType.class)
    public JAXBElement<XmlModifierType> createFeatureTypeModifier(XmlModifierType value) {
        return new JAXBElement<XmlModifierType>(_ItemTypeModifier_QNAME, XmlModifierType.class, XmlFeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlFeatureType.class)
    public JAXBElement<String> createFeatureTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlFeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "text", scope = XmlFeatureType.class)
    public JAXBElement<String> createFeatureTypeText(String value) {
        return new JAXBElement<String>(_TraitTypeText_QNAME, String.class, XmlFeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlFeatureType.class)
    public JAXBElement<String> createFeatureTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlFeatureType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlSizeEnum }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "size", scope = XmlRaceType.class)
    public JAXBElement<XmlSizeEnum> createRaceTypeSize(XmlSizeEnum value) {
        return new JAXBElement<XmlSizeEnum>(_MonsterTypeSize_QNAME, XmlSizeEnum.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlModifierType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "modifier", scope = XmlRaceType.class)
    public JAXBElement<XmlModifierType> createRaceTypeModifier(XmlModifierType value) {
        return new JAXBElement<XmlModifierType>(_ItemTypeModifier_QNAME, XmlModifierType.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "name", scope = XmlRaceType.class)
    public JAXBElement<String> createRaceTypeName(String value) {
        return new JAXBElement<String>(_TraitTypeName_QNAME, String.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlTraitType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "trait", scope = XmlRaceType.class)
    public JAXBElement<XmlTraitType> createRaceTypeTrait(XmlTraitType value) {
        return new JAXBElement<XmlTraitType>(_BackgroundTypeTrait_QNAME, XmlTraitType.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "ability", scope = XmlRaceType.class)
    public JAXBElement<String> createRaceTypeAbility(String value) {
        return new JAXBElement<String>(_RaceTypeAbility_QNAME, String.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "speed", scope = XmlRaceType.class)
    public JAXBElement<BigInteger> createRaceTypeSpeed(BigInteger value) {
        return new JAXBElement<BigInteger>(_MonsterTypeSpeed_QNAME, BigInteger.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "proficiency", scope = XmlRaceType.class)
    public JAXBElement<String> createRaceTypeProficiency(String value) {
        return new JAXBElement<String>(_TraitTypeProficiency_QNAME, String.class, XmlRaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "spellAbility", scope = XmlRaceType.class)
    public JAXBElement<String> createRaceTypeSpellAbility(String value) {
        return new JAXBElement<String>(_ClassTypeSpellAbility_QNAME, String.class, XmlRaceType.class, value);
    }

}
