//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2022.05.28 at 10:45:07 AM EDT
//

package dev.ebullient.fc5.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for slotsType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="slotsType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>integerList">
 *       &lt;attribute name="optional" type="{}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "slotsType", propOrder = {
        "value"
})
public class XmlSlotsType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "optional")
    protected String optional;

    /**
     * Gets the value of the value property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the optional property.
     *
     * @return
     *         possible object is
     *         {@link String }
     *
     */
    public String getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     *
     * @param value
     *        allowed object is
     *        {@link String }
     *
     */
    public void setOptional(String value) {
        this.optional = value;
    }

}
